cors:
  originPatterns: http://localhost:8080,http://localhost:3000
security:
  jwt: 
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/expense_management_tool?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
     charset: UTF-8
     enabled: true
     force: true
logging:
  level:
    root: INFO
  file:
    name: app-api.log
    path: /home/app/logs/
springdoc:
  pathsToMatch: /api/**/**/**
  swagger-ui:
    use-root-path: true